build: BotCode/taleNt.cpp BotCode/*.hpp BotCode/*.h Network/*.h
	g++ -std=c++17 -Wall -Wextra -O3 -march=native BotCode/taleNt.cpp -o BotCode/taleNt

run: BotCode/taleNt
	./BotCode/taleNt

clean: BotCode/taleNt
	rm BotCode/taleNt
